# Generated by Django 6.1.2 on 2026-10-10 21:09

import django.db.models.deletion
from django.db import migrations, models

import judge.models.contest


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0240_language_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'badge', 'verbose_name_plural': 'badges'},
        ),
        migrations.AlterModelOptions(
            name='commentlock',
            options={
                'permissions': (('override_comment_lock', 'Override comment lock'),),
                'verbose_name': 'comment lock',
                'verbose_name_plural': 'comment locks',
            },
        ),
        migrations.AlterModelOptions(
            name='contestannouncement',
            options={
                'verbose_name': 'contest announcement',
                'verbose_name_plural': 'contest announcements',
            },
        ),
        migrations.AlterModelOptions(
            name='generalissue',
            options={
                'verbose_name': 'general issue',
                'verbose_name_plural': 'general issues',
            },
        ),
        migrations.AlterModelOptions(
            name='problemclarification',
            options={
                'verbose_name': 'problem clarification',
                'verbose_name_plural': 'problem clarifications',
            },
        ),
        migrations.AlterModelOptions(
            name='problemdata',
            options={
                'verbose_name': 'problem data',
                'verbose_name_plural': 'problem data',
            },
        ),
        migrations.AlterModelOptions(
            name='problemtestcase',
            options={
                'verbose_name': 'problem test case',
                'verbose_name_plural': 'problem test cases',
            },
        ),
        migrations.AlterModelOptions(
            name='runtimeversion',
            options={
                'verbose_name': 'runtime version',
                'verbose_name_plural': 'runtime versions',
            },
        ),
        migrations.AlterModelOptions(
            name='submissionsource',
            options={
                'verbose_name': 'submission source',
                'verbose_name_plural': 'submission sources',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='tagdata',
            options={'verbose_name': 'tag data', 'verbose_name_plural': 'tag data'},
        ),
        migrations.AlterModelOptions(
            name='taggroup',
            options={'verbose_name': 'tag group', 'verbose_name_plural': 'tag groups'},
        ),
        migrations.AlterModelOptions(
            name='tagproblem',
            options={
                'verbose_name': 'tag problem',
                'verbose_name_plural': 'tag problems',
            },
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={
                'verbose_name': 'ticket message',
                'verbose_name_plural': 'ticket messages',
            },
        ),
        migrations.AlterField(
            model_name='blogvote',
            name='blog',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='votes',
                to='judge.blogpost',
                verbose_name='blog',
            ),
        ),
        migrations.AlterField(
            model_name='blogvote',
            name='score',
            field=models.IntegerField(verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='blogvote',
            name='voter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='voted_blogs',
                to='judge.profile',
                verbose_name='voter',
            ),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='votes',
                to='judge.comment',
                verbose_name='comment',
            ),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='score',
            field=models.IntegerField(verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='voter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='voted_comments',
                to='judge.profile',
                verbose_name='voter',
            ),
        ),
        migrations.AlterField(
            model_name='contest',
            name='authors',
            field=models.ManyToManyField(
                help_text='These users will be able to edit the contest.',
                related_name='authors+',
                to='judge.profile',
                verbose_name='authors',
            ),
        ),
        migrations.AlterField(
            model_name='contest',
            name='curators',
            field=models.ManyToManyField(
                blank=True,
                help_text='These users will be able to edit the contest, but will not be listed as authors.',
                related_name='curators+',
                to='judge.profile',
                verbose_name='curators',
            ),
        ),
        migrations.AlterField(
            model_name='contest',
            name='replay_version',
            field=models.PositiveIntegerField(default=0, verbose_name='replay version'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='show_submission_list',
            field=models.BooleanField(
                default=False,
                help_text='Allow contestants to view submission list of others in contest time',
                verbose_name='show submission list',
            ),
        ),
        migrations.AlterField(
            model_name='contest',
            name='testers',
            field=models.ManyToManyField(
                blank=True,
                help_text='These users will be able to view the contest, but not edit it.',
                related_name='testers+',
                to='judge.profile',
                verbose_name='testers',
            ),
        ),
        migrations.AlterField(
            model_name='contestmoss',
            name='language',
            field=models.CharField(max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='contestmoss',
            name='submission_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='submission count'
            ),
        ),
        migrations.AlterField(
            model_name='contestmoss',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='max_submissions',
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text='Maximum number of submissions for this problem, or leave blank for no limit.',
                null=True,
                validators=[
                    judge.models.contest.MinValueOrNoneValidator(
                        1, "Why include a problem you can't submit to?"
                    )
                ],
                verbose_name='max submissions',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='current_consumed_credit',
            field=models.FloatField(
                default=0,
                help_text='Total used credit this month',
                verbose_name='current consumed credit',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='free_credit',
            field=models.FloatField(
                db_column='monthly_credit',
                default=0,
                help_text='Remaining free credits for the current month',
                verbose_name='free credit',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='member_count',
            field=models.IntegerField(default=0, verbose_name='member count'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='monthly_free_credit_limit',
            field=models.FloatField(
                default=10800,
                help_text='Amount of free credits allocated each month',
                verbose_name='monthly free credit limit',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='paid_credit',
            field=models.FloatField(
                db_column='available_credit',
                default=0,
                help_text='Remaining purchased credits',
                verbose_name='paid credit',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='performance_points',
            field=models.FloatField(default=0, verbose_name='performance points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='allow_view_feedback',
            field=models.BooleanField(
                default=False,
                help_text='Allow user to view checker feedback.',
                verbose_name='allow view feedback',
            ),
        ),
        migrations.AlterField(
            model_name='problem',
            name='license',
            field=models.ForeignKey(
                blank=True,
                help_text='The license under which this problem is published.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='judge.license',
                verbose_name='license',
            ),
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_circuit',
            field=models.BooleanField(default=False, verbose_name='short circuit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(
                blank=True,
                help_text='Show to banned user in login page.',
                null=True,
                verbose_name='ban reason',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contribution_points',
            field=models.IntegerField(default=0, verbose_name='contribution points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='performance_points',
            field=models.FloatField(default=0, verbose_name='performance points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='problem_count',
            field=models.IntegerField(default=0, verbose_name='problem count'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=None, null=True, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vnoj_points',
            field=models.IntegerField(default=0, verbose_name='VNOJ points'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_testcase',
            field=models.IntegerField(default=0, verbose_name='current testcase'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='judge.problem',
                verbose_name='problem',
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='judge.profile',
                verbose_name='user',
            ),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='problem',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='judge.tagproblem',
                verbose_name='problem',
            ),
        ),
    ]
