name: 'django'
on:
  pull_request:
    branches: [main]

concurrency:
  group: django-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  migrations:
    name: check
    permissions:
      contents: read
    uses: tloi-dalat/reusable-workflow/.github/workflows/django-migration-check.yaml@main
    with:
      python-version: '3.12'
      requirements: requirements.txt
      settings-file: .ci.settings.py

  i18n:
    name: check
    permissions:
      contents: read
    uses: tloi-dalat/reusable-workflow/.github/workflows/django-i18n-check.yaml@main
    with:
      python-version: '3.12'
      requirements: requirements.txt
      settings-file: .ci.settings.py
      settings-target: dmoj/local_settings.py
      source-locale: en
      compile: |
        python manage.py compilemessages
        python manage.py compilejsi18n
      template-globs: 'templates/**/*.html templates/**/*.txt'
      makemessages: |
        -e py,html,txt -i node_modules -i static -i sass_processed -i resources/libs -i resources/vnoj
        -d djangojs -i node_modules -i static -i sass_processed -i resources/libs -i resources/vnoj
